type: object
properties:
  customInstructionsEnabled:
    type: boolean
    description: Indicator whether custom password instructions feature is enabled. The default value is false.
  digitTokenEnabled:
    type: boolean
    description: Indicator whether "digit token" feature is enabled. The default value is false.
    example: true
  digitTokenDurationMinutes:
    type: integer
    description: The duration of "digit token" in minutes. The default value is 5.
    example: 10
  digitTokenLength:
    type: integer
    description: The length of "digit token". The default value is 6.
    example: 9