get:
  tags:
    - Managed Clusters
  summary: get ManagedCluster Log Configuration for a specified cluster
  description: Get log configuration for a managed cluster.
  operationId: getClientLogConfiguration
  parameters:
    - name: id
      in: path
      description: ID of the ManagedCluster to get log configuration for
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: aClusterId
  responses:
    "200":
      description: ManagedCluster log configuration matching the given cluster ID
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/ClientLogConfiguration.yaml'
    "400":
      $ref: '../../v3/responses/400.yaml'
    "403":
      $ref: '../../v3/responses/403.yaml'
    "404":
      $ref: '../../v3/responses/404.yaml'
  security:
    - oauth2: [idn:managed-cluster-log-config:read]
put:
  tags:
    - Managed Clusters
  summary: Update log configuration for a specified cluster.
  description: Update log configuration for a managed cluster.
  operationId: updateClientLogConfiguration
  parameters:
    - name: id
      in: path
      description: ID of the ManagedCluster to update log configuration for
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: aClusterId
  requestBody:
    description: ClientLogConfiguration for the given ManagedCluster
    content:
      application/json:
        schema:
          $ref: '../schemas/ClientLogConfiguration.yaml'
    required: true
  responses:
    "200":
      description: Responds with updated ClientLogConfiguration for the given ManagedCluster.
      content:
        application/json:
          schema:
            $ref: '../schemas/ClientLogConfiguration.yaml'
    "400":
      $ref: '../../v3/responses/400.yaml'
    "403":
      $ref: '../../v3/responses/403.yaml'
    "404":
      $ref: '../../v3/responses/404.yaml'
  security:
    - oauth2: [idn:managed-cluster-log-config:write]
